index:
    path: '/'
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction'
    defaults:
        path: '/admin/login'
        permanent: true

home:
    path: '/'
